name: PR Linting / Unit Testing

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: 'read'

jobs:
  lint:
    name: Linting / Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit tox

      - name: Run pre-commit
        run: pre-commit run --all-files
